name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build
        run: |
          sudo apt-get update
          sudo apt-get -y install nasm
          make
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: tests
        run: |
          sudo apt-get update
          sudo apt-get -y install nasm
          make
          ./scripts/test.sh